# Configure this Discovery Server
eureka:
  instance:
    hostname: discover-service.cfapps.io
  client: 
    registerWithEureka: false
    fetchRegistry: false

# HTTP (Tomcat) port
server:
  port: 1111   
